<div><x-ui.container class="py-8 sm:py-10 lg:py-14"><div class="mx-auto max-w-4xl space-y-8">
    <header><a class="text-sm font-medium text-catalyst-primary underline underline-offset-4" href="{{ route('dashboard.registration.index') }}">Back to registrations</a><p class="mt-7 text-xs font-semibold tracking-[0.2em] text-catalyst-primary">{{ $competitionModel->code->value }}</p><h1 class="mt-3 font-display text-3xl font-semibold sm:text-5xl">{{ $competitionModel->name }}</h1><p class="mt-4 max-w-2xl text-sm leading-6 text-catalyst-ink/75">{{ $competitionModel->description }}</p></header>
    @if ($feedback)<p class="border border-status-success/30 bg-status-success/10 p-4 text-sm text-status-success-ink" role="status">{{ $feedback }}</p>@endif
    <section class="grid gap-4 border border-catalyst-grey/30 bg-white p-5 sm:grid-cols-3 sm:p-6"><div><p class="text-xs text-catalyst-muted">Registration fee</p><p class="mt-2 font-semibold">IDR {{ number_format((float) $competitionModel->registration_fee, 0, ',', '.') }}</p></div><div><p class="text-xs text-catalyst-muted">Registration</p><p class="mt-2 font-semibold">{{ $registration?->status->value ?? 'NOT REGISTERED' }}</p></div><div><p class="text-xs text-catalyst-muted">Payment</p><div class="mt-2"><x-dashboard.status-pill :label="$paymentStatus['label']" :tone="$paymentStatus['tone']" /></div></div></section>
    @if ($team)<section class="border border-catalyst-grey/30 bg-white p-5 sm:p-6"><div class="flex justify-between gap-4"><div><h2 class="font-display text-xl font-semibold">Team review</h2><p class="mt-2 text-sm text-catalyst-ink/70">{{ $team->name }} · {{ $team->institution }}</p></div><a class="text-sm font-medium text-catalyst-primary underline underline-offset-4" href="{{ route('dashboard.team.index') }}">Manage team</a></div><ul class="mt-5 divide-y divide-catalyst-grey/20 border-y border-catalyst-grey/20"><li class="flex justify-between gap-4 py-3 text-sm"><span>{{ $team->captain->name }} (Captain)</span><span>{{ $team->captain->hasCompleteKtm() ? 'KTM ready' : 'KTM missing' }}</span></li>@foreach($team->members as $member)<li class="flex justify-between gap-4 py-3 text-sm"><span>{{ $member->name }}</span><span>{{ $member->hasCompleteKtm() ? 'KTM ready' : 'KTM missing' }}</span></li>@endforeach</ul></section>@endif
    @if ($registration)@if ($registration->payment?->status?->value === 'REJECTED')<section class="border border-status-error/30 bg-status-error/5 p-5"><h2 class="font-display text-xl font-semibold">Payment rejected</h2><p class="mt-2 text-sm">Corrections are handled through the Catalyst contact person.</p></section>@endif<a class="inline-flex w-full justify-center bg-catalyst-primary px-4 py-3 font-medium text-white sm:w-auto" href="{{ $paymentUrl }}">{{ $registration->payment?->status ? 'View Payment Status' : 'Continue to Payment' }}</a>
    @elseif ($blockReason)<section class="border border-status-warning/30 bg-status-warning/5 p-5"><h2 class="font-display text-xl font-semibold">Registration unavailable</h2><p class="mt-2 text-sm leading-6">{{ $blockReason }}</p>@if (! $team || ! $team?->hasCompleteKtm())<a class="mt-4 inline-flex bg-catalyst-primary px-4 py-3 text-sm font-medium text-white" href="{{ route('dashboard.team.index') }}">Complete Team</a>@endif</section>
    @elseif ($canRegister)<button class="bg-catalyst-primary px-5 py-3 font-medium text-white" type="button" wire:click="openConfirmation">Register this team</button>@endif
</div></x-ui.container>
@if ($showConfirm)<dialog x-data x-init="$el.showModal()" class="fixed inset-0 m-auto w-[calc(100%-2rem)] max-w-md border-0 bg-white p-6 shadow-xl backdrop:bg-catalyst-ink/40"><h2 class="font-display text-2xl font-semibold">Confirm registration</h2><p class="mt-3 text-sm leading-6 text-catalyst-ink/75">Register {{ $team?->name }} for {{ $competitionModel->name }}?</p><div class="mt-6 flex justify-end gap-3"><button class="border border-catalyst-grey/50 px-4 py-3 text-sm" type="button" wire:click="cancelConfirmation">Cancel</button><button class="bg-catalyst-primary px-4 py-3 text-sm font-medium text-white" type="button" wire:click="submitRegistration">Confirm registration</button></div></dialog>@endif
</div>
